# Generated by Django 3.0.6 on 2020-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_auto_20200627_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='userid',
            new_name='password',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
