# Generated by Django 3.0.6 on 2020-06-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_auto_20200627_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('ordereditems', models.CharField(max_length=30)),
            ],
        ),
    ]
