# Generated by Django 3.0.6 on 2020-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='userid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
