# Generated by Django 3.0.6 on 2020-06-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0009_ordermodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='phoneno',
        ),
    ]
